<!DOCTYPE html><html lang="zh-CN"><head><meta name="generator" content="Hexo 3.9.0"><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description" content="随感，遥感，机器学习....想到什么写什么"><title>CAD二次开发问题集中解决 | 吴蔚</title><link rel="stylesheet" type="text/css" href="/css/style.css?v=0.0.0"><link rel="stylesheet" type="text/css" href="//lib.baomitu.com/normalize/8.0.1/normalize.min.css"><link rel="stylesheet" type="text/css" href="//lib.baomitu.com/pure/1.0.0/pure-min.css"><link rel="stylesheet" type="text/css" href="//lib.baomitu.com/pure/1.0.0/grids-responsive-min.css"><link rel="stylesheet" href="//lib.baomitu.com/font-awesome/4.7.0/css/font-awesome.min.css"><script type="text/javascript" src="//lib.baomitu.com/jquery/3.3.1/jquery.min.js"></script><link rel="icon" mask sizes="any" href="/favicon.ico"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="apple-touch-icon-precomposed" href="/apple-touch-icon.png"><link rel="alternate" type="application/atom+xml" href="/atom.xml"></head><body><div class="body_container"><div id="header"><div class="site-name"><h1 class="hidden">CAD二次开发问题集中解决</h1><a id="logo" href="/.">吴蔚</a><p class="description">生命不息，折腾不止！</p></div><div id="nav-menu"><a class="current" href="/."><i class="fa fa-home"> 首页</i></a><a href="/archives/"><i class="fa fa-archive"> 归档</i></a><a href="/about/"><i class="fa fa-user"> 关于</i></a><a href="/atom.xml"><i class="fa fa-rss"> 订阅</i></a></div></div><div class="pure-g" id="layout"><div class="pure-u-1 pure-u-md-3-4"><div class="content_container"><div class="post"><h1 class="post-title">CAD二次开发问题集中解决</h1><div class="post-meta">Sep 7, 2017<span> | </span><span class="category"><a href="/categories/学习/">学习</a></span></div><a class="disqus-comment-count" href="/2017/09/07/CAD二次开发问题集中解决/#vcomment"><span class="valine-comment-count" data-xid="/2017/09/07/CAD二次开发问题集中解决/"></span><span> 条评论</span></a><div class="post-content"><p>使用了一段时间的AutoCAD后遇到了很多问题，感谢一些网上的大神给我提出了很多宝贵的意见和指导，虽然有时候会很麻烦，有时候会让我绞尽脑汁，有时候会很抓狂但是问题总是在一步一步的解决，当然啦对于新的帮助最大的还是万能的百度，但是有时候网上的东西写的比较简略或者由于版本过于陈旧而缺少了参考的价值，而自己获得了很多帮助所以也想着写一些东西出来为后来学习的人做贡献。<br>好了废话不多说，直接上干活，说说自己在开发的过程中所面临的问题以及自己的解决方式，当然我提出的解决方式可能不是最好的额，不过也可以让大家作为参考：  </p>
<ul>
<li>问题1：在选取对象的过程中如果在一个Block中则无法获取对象的所有点，只有边界点的问题：</li>
</ul>
<p>对于问题1也一度让我无比纠结，很多时候在CAD中为了方便我们往往会将实体建立为一个Block，然后直接操作这个Block，这样可以极大的简化操作，可是在我们使用代码获取这个实体就变得有些困难了，我们对实体的操作往往要操作到底层的点和线上，所以我们希望能够获取Block中每一个点，最简单的想法就是把Block炸开，可是也有可能出现Block嵌套的情况，所以这个炸开的过程需要递归的进行，整个炸开过程的代码为：<br><figure class="highlight c++"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetPointsInEntity</span><span class="params">(Database db,Transaction trans,BlockTable bt,Entity ent,List&lt;Point3dCollection&gt; pointCollections)</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">if</span> (ent is BlockReference)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">//递归获取所有块的实体</span></span><br><span class="line">        BlockReference brf = ent as BlockReference;</span><br><span class="line">        DBObjectCollection ents = (DBObjectCollection)GetEntitiesInBlock(db, trans, brf); <span class="comment">//这句是得到块中的实体</span></span><br><span class="line">        foreach (var obj in ents)</span><br><span class="line">        &#123;</span><br><span class="line">            Entity ent1 = obj as Entity;</span><br><span class="line">            GetPointsInEntity(db, trans, bt, ent1, pointCollections);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        Point3dCollection pnt3ds = <span class="keyword">new</span> Point3dCollection();</span><br><span class="line">        IntegerCollection intcollect = <span class="keyword">new</span> IntegerCollection();</span><br><span class="line">        IntegerCollection geoIndex = <span class="keyword">new</span> IntegerCollection();</span><br><span class="line">        ent.GetGripPoints(pnt3ds, intcollect, geoIndex);</span><br><span class="line">        pointCollections.Add(pnt3ds);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>上面的代码就是将所有的块炸开然后将线的信息保存到一个点列中，我们可以看到整个递归的过程，通过不停的判断实体是否是Block，如果是则炸开，如果不是则直接获取信息，这样我们能够获取实体所有信息。ok知道了这个相信大家都能够很好的获取Block，下面我们要面临这样一个问题，如果实际上我只是想获取点信息并不是真的想将Block炸开，这可如何是好，实际上也很简单，我们在完成以上工作后不需要commit提交，则炸开操作不会执行，而我们又获取了所有块的信息。</p>
<ul>
<li>问题2：实现AutoCAD中的Panel拖动，靠边效果：</li>
</ul>
<p>实际上在处理过程中我并没有想过要实现这样的效果，但是领导看完之后觉得我做的界面太简陋因此要求提供一个这样的效果，为此我在网上找了不少资料，最后解决了这个问题，解决方案为，首先建立一个自定义的界面，界面没有边框可以嵌入Panel中，然后AutoCAD提供了一个Panel，将自定义的界面嵌入其中就可以了，具体代码如下：<br><figure class="highlight c++"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">Autodesk.AutoCAD.Windows.PaletteSet ps = <span class="keyword">new</span> Autodesk.AutoCAD.Windows.PaletteSet(<span class="string">"导线绘制"</span>);</span><br><span class="line"> AutoWire constructControl = <span class="keyword">new</span> AutoWire();</span><br><span class="line"></span><br><span class="line"> ps.Visible = <span class="literal">true</span>;</span><br><span class="line"></span><br><span class="line"> ps.Style = Autodesk.AutoCAD.Windows.PaletteSetStyles.ShowAutoHideButton | Autodesk.AutoCAD.Windows.PaletteSetStyles.ShowCloseButton;</span><br><span class="line"> ps.Dock = Autodesk.AutoCAD.Windows.DockSides.None;</span><br><span class="line"> ps.MinimumSize = <span class="keyword">new</span> System.Drawing.Size(<span class="number">250</span>, <span class="number">450</span>);</span><br><span class="line"> ps.Size = <span class="keyword">new</span> System.Drawing.Size(<span class="number">250</span>, <span class="number">450</span>);</span><br><span class="line"> ps.Add(<span class="string">"导线绘制"</span>, constructControl);</span><br><span class="line"></span><br><span class="line"> ps.Visible = <span class="literal">true</span>;</span><br></pre></td></tr></table></figure></p>
<p>下面分析上述代码，第一行为新建一个PaletteSet，这个空间是AutoCAD提供的控件，通过此控件能够构造一个停靠窗口，第二行是新建一个自定义控件，然后设置停靠窗的属性，最后我们讲自定义的控件添加到这个PaletteSet中，完成我们的构造过程，构造的结果为：<br><img src="https://lh3.googleusercontent.com/-omMUHiqpZR8/WbFBAPoHjcI/AAAAAAAACVc/1TnnUh0WOgAEt0AH65yJfMcNHf31CdoyACLcBGAs/s0/QQ%25E6%2588%25AA%25E5%259B%25BE20170907152331.png" alt="效果图" title="QQ截图20170907152331.png"><br>从上图我们可以看到，实际通过以上操作我们已经构造了一个可以停靠额窗口了，可是实际上窗口依然不好看，请原谅我无法言说的审美观。</p>
<ul>
<li>问题3：如何在CAD中点击一个点获取这个点的坐标？</li>
</ul>
<p>这个问题也是随着需求的变化而产生的，不过这也是一个十分有意义的问题，在进行CAD操作中往往存在着我自己点几个点，然后需要按照一定的算法自动构造图形的过程，而这个过程首先要面临的一个问题就是如何在CAD中点击一个点并获取这个点的坐标，实际上这也不是一个多么困难的功能但是网上的资源同样存在着不全面或者有些的博客给出的代码根本就没有经过测试的问题，下面是我的解决方案：<br><figure class="highlight c++"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Point3d <span class="title">MainOptFunc_Point</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    Point3d pnt = <span class="keyword">new</span> Point3d(<span class="number">-1</span>,<span class="number">-1</span>,<span class="number">-1</span>);</span><br><span class="line"></span><br><span class="line">    Document doc = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;</span><br><span class="line">    Database db = doc.Database;</span><br><span class="line"></span><br><span class="line">    Editor ed = doc.Editor;</span><br><span class="line">    PromptPointResult acPointPromot = ed.GetPoint(<span class="string">"获取点的坐标"</span>);</span><br><span class="line">    <span class="keyword">if</span> (acPointPromot.Status == PromptStatus.OK)</span><br><span class="line">    &#123;</span><br><span class="line">        Transaction tran = doc.TransactionManager.StartTransaction();</span><br><span class="line">        <span class="keyword">using</span> (tran)</span><br><span class="line">        &#123;</span><br><span class="line">            pnt = acPointPromot.Value;</span><br><span class="line">            <span class="keyword">double</span> x = pnt.X;</span><br><span class="line">            <span class="keyword">double</span> y = pnt.Y;</span><br><span class="line">            <span class="keyword">double</span> z = pnt.Z;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> pnt;</span><br><span class="line"> &#125;</span><br></pre></td></tr></table></figure></p>
<p>实际上很简单，返回值就是我们鼠标点击获取的点，比较选取实体和选点的不同我们发现主要在于Editor中获取函数有区别，实际上将函数封装成一个接口就能够很方便的进行选点操作了。<br>顺便提一句，以上程序的开发环境都是VS2010 AutoCAD2012。到此为止已经把面临到的几个棘手的问题都处理了，如果大家还有什么问题可以给我发邮件提问：<a href="mailto:wuwei_cug@163.com" target="_blank" rel="noopener">wuwei_cug@163.com</a></p>
</div><div class="tags"><a href="/tags/开发/">开发</a></div><div class="post-nav"><a class="pre" href="/2017/09/10/tensorflow-十五弹/">tensorflow-十五弹</a><a class="next" href="/2017/09/06/有罪或无罪/">有罪或无罪</a></div><div id="vcomment"></div><script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script><script src="//unpkg.com/valine@latest/dist/Valine.min.js"></script><script>var notify = 'true' == true ? true : false;
var verify = 'true' == true ? true : false;
var GUEST_INFO = ['nick','mail','link'];
var guest_info = 'nick,mail,link'.split(',').filter(function(item){
  return GUEST_INFO.indexOf(item) > -1
});
guest_info = guest_info.length == 0 ? GUEST_INFO :guest_info;
window.valine = new Valine({
  el:'#vcomment',
  notify:notify,
  verify:verify,
  appId:'uHNJtTxLkcGm3VRtuRGk53hb-gzGzoHsz',
  appKey:'h8s1QFO2dLQ62H0axpKB6WnD',
  placeholder:'说点啥吧...',
  avatar:'mm',
  guest_info:guest_info,
  pageSize:'10'
})</script></div></div></div><div class="pure-u-1-4 hidden_mid_and_down"><div id="sidebar"><div class="widget"><form class="search-form" action="//www.baidu.com/baidu" method="get" accept-charset="utf-8" target="_blank"><input type="search" name="word" maxlength="20" placeholder="Search"><input type="hidden" name="si" value="http://www.wuweiblog.com"><input name="tn" type="hidden" value="bds"><input name="cl" type="hidden" value="3"><input name="ct" type="hidden" value="2097152"><input name="s" type="hidden" value="on"></form></div><div class="widget"><div class="widget-title"><i class="fa fa-folder-o"> 分类</i></div><ul class="category-list"><li class="category-list-item"><a class="category-list-link" href="/categories/书评/">书评</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/图像处理/">图像处理</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/学习/">学习</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/小说/">小说</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/影评/">影评</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/数学/">数学</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/游戏/">游戏</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/点云处理/">点云处理</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/算法/">算法</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/随感/">随感</a></li></ul></div><div class="widget"><div class="widget-title"><i class="fa fa-star-o"> 标签</i></div><div class="tagcloud"><a href="/tags/ArcGIS，前端开发/" style="font-size: 15px;">ArcGIS，前端开发</a> <a href="/tags/ArcGIS环境配置/" style="font-size: 15px;">ArcGIS环境配置</a> <a href="/tags/ArcGIS开发/" style="font-size: 15px;">ArcGIS开发</a> <a href="/tags/开发/" style="font-size: 15px;">开发</a> <a href="/tags/linux-学习/" style="font-size: 15px;">linux 学习</a> <a href="/tags/学习/" style="font-size: 15px;">学习</a> <a href="/tags/数学/" style="font-size: 15px;">数学</a> <a href="/tags/图像处理数学原理/" style="font-size: 15px;">图像处理数学原理</a> <a href="/tags/效率/" style="font-size: 15px;">效率</a> <a href="/tags/系统架构-学习/" style="font-size: 15px;">系统架构 学习</a> <a href="/tags/算法/" style="font-size: 15px;">算法</a> <a href="/tags/机器学习/" style="font-size: 15px;">机器学习</a> <a href="/tags/机器学习，图像处理/" style="font-size: 15px;">机器学习，图像处理</a> <a href="/tags/tensorflow学习/" style="font-size: 15px;">tensorflow学习</a> <a href="/tags/随感/" style="font-size: 15px;">随感</a> <a href="/tags/Mary-and-Max，影评/" style="font-size: 15px;">Mary and Max，影评</a> <a href="/tags/沉默的大多数，书评/" style="font-size: 15px;">沉默的大多数，书评</a> <a href="/tags/断舍离，书评/" style="font-size: 15px;">断舍离，书评</a> <a href="/tags/雪中悍刀行-书评/" style="font-size: 15px;">雪中悍刀行,书评</a> <a href="/tags/呼兰河传-书评/" style="font-size: 15px;">呼兰河传,书评</a> <a href="/tags/将夜-书评/" style="font-size: 15px;">将夜,书评</a> <a href="/tags/中国经济2019-时间的答案/" style="font-size: 15px;">中国经济2019,时间的答案</a> <a href="/tags/未来简史-书评/" style="font-size: 15px;">未来简史,书评</a> <a href="/tags/图像处理/" style="font-size: 15px;">图像处理</a> <a href="/tags/潜规则-书评/" style="font-size: 15px;">潜规则,书评</a> <a href="/tags/你好疯子，影评/" style="font-size: 15px;">你好疯子，影评</a> <a href="/tags/熊镇-书评/" style="font-size: 15px;">熊镇,书评</a> <a href="/tags/openMVG-openMVS学习/" style="font-size: 15px;">openMVG openMVS学习</a> <a href="/tags/喜剧之王，影评/" style="font-size: 15px;">喜剧之王，影评</a> <a href="/tags/The-Legend-of-1900/" style="font-size: 15px;">The Legend of 1900</a> <a href="/tags/随感-摄影测量/" style="font-size: 15px;">随感-摄影测量</a> <a href="/tags/随感，毕业/" style="font-size: 15px;">随感，毕业</a> <a href="/tags/校正方法，控制点，光束法平差/" style="font-size: 15px;">校正方法，控制点，光束法平差</a> <a href="/tags/linux学习/" style="font-size: 15px;">linux学习</a> <a href="/tags/月亮与六便士/" style="font-size: 15px;">月亮与六便士</a> <a href="/tags/电影十二公民/" style="font-size: 15px;">电影十二公民</a> <a href="/tags/随感，死亡/" style="font-size: 15px;">随感，死亡</a> <a href="/tags/小说/" style="font-size: 15px;">小说</a> <a href="/tags/V字仇杀队-浪潮，影评/" style="font-size: 15px;">V字仇杀队,浪潮，影评</a> <a href="/tags/随感－代码重构/" style="font-size: 15px;">随感－代码重构</a> <a href="/tags/遗愿清单，影评/" style="font-size: 15px;">遗愿清单，影评</a> <a href="/tags/指环王，这个杀手不太冷/" style="font-size: 15px;">指环王，这个杀手不太冷</a> <a href="/tags/R-学习/" style="font-size: 15px;">R 学习</a> <a href="/tags/点云处理/" style="font-size: 15px;">点云处理</a> <a href="/tags/爱乐之城，影评/" style="font-size: 15px;">爱乐之城，影评</a> <a href="/tags/狗子日记/" style="font-size: 15px;">狗子日记</a> <a href="/tags/一个叫欧维的男人决定去死，书评/" style="font-size: 15px;">一个叫欧维的男人决定去死，书评</a> <a href="/tags/星际穿越，影评/" style="font-size: 15px;">星际穿越，影评</a> <a href="/tags/图像处理的数学原理/" style="font-size: 15px;">图像处理的数学原理</a> <a href="/tags/社交网络，影评/" style="font-size: 15px;">社交网络，影评</a> <a href="/tags/共产党宣言/" style="font-size: 15px;">共产党宣言</a> <a href="/tags/秒速五厘米/" style="font-size: 15px;">秒速五厘米</a> <a href="/tags/海涛之声，影评/" style="font-size: 15px;">海涛之声，影评</a> <a href="/tags/白日梦想家，影评/" style="font-size: 15px;">白日梦想家，影评</a> <a href="/tags/饥荒/" style="font-size: 15px;">饥荒</a></div></div><div class="widget"><div class="widget-title"><i class="fa fa-file-o"> 最近文章</i></div><ul class="post-list"><li class="post-list-item"><a class="post-list-link" href="/2021/01/31/社会与资本/">社会与资本</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/12/25/有那么一瞬间/">有那么一瞬间</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/12/06/死亡记录/">死亡记录</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/12/06/不读书-九/">不读书(九)</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/11/16/挣扎/">挣扎</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/11/02/点到三维空间直线距离计算以向量方式计算/">点到三维空间直线距离计算以向量方式计算</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/10/30/ArcGIS-结合-WebGL动态渲染1/">ArcGIS 结合 WebGL动态渲染1</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/10/30/狗子日记十一月四号/">狗子日记十一月四号</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/10/18/点云处理总结/">点云处理总结</a></li><li class="post-list-item"><a class="post-list-link" href="/2020/09/13/关于方向/">关于方向</a></li></ul></div><div class="widget"><div class="widget-title"><i class="fa fa-external-link"> 友情链接</i></div><ul></ul><a href="https://github.com/RemoteSensingFrank" title="Github" target="_blank">Github</a><ul></ul><a href="http://www.example2.com/" title="site-name2" target="_blank">site-name2</a><ul></ul><a href="http://www.example3.com/" title="site-name3" target="_blank">site-name3</a></div></div></div><div class="pure-u-1 pure-u-md-3-4"><div id="footer">Copyright © 2021 <a href="/." rel="nofollow">吴蔚.</a> Powered by<a rel="nofollow" target="_blank" href="https://hexo.io"> Hexo.</a><a rel="nofollow" target="_blank" href="https://github.com/tufu9441/maupassant-hexo"> Theme</a> by<a rel="nofollow" target="_blank" href="https://github.com/pagecho"> Cho.</a></div></div></div><a class="show" id="rocket" href="#top"></a><script type="text/javascript" src="/js/totop.js?v=0.0.0" async></script><script type="text/javascript" src="//lib.baomitu.com/fancybox/3.5.2/jquery.fancybox.min.js" async></script><script type="text/javascript" src="/js/fancybox.js?v=0.0.0" async></script><link rel="stylesheet" type="text/css" href="//lib.baomitu.com/fancybox/3.5.2/jquery.fancybox.min.css"><script type="text/javascript" src="/js/codeblock-resizer.js?v=0.0.0"></script><script type="text/javascript" src="/js/smartresize.js?v=0.0.0"></script></div></body></html>